-- MySQL Script generated by MySQL Workbench
-- Fri Jul 29 23:58:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_gota_em_gota
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_gota_em_gota
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_gota_em_gota` DEFAULT CHARACTER SET utf8 ;
USE `db_gota_em_gota` ;

-- -----------------------------------------------------
-- Table `db_gota_em_gota`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gota_em_gota`.`tb_usuario` (
  `id_usuario` BIGINT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `usuario_cpf` VARCHAR(255) NOT NULL,
  `usuario_cnpj` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gota_em_gota`.`tb_subtemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gota_em_gota`.`tb_subtemas` (
  `id_temas` BIGINT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_temas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gota_em_gota`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gota_em_gota`.`tb_postagens` (
  `id_postagens` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `texto` VARCHAR(2000) NOT NULL,
  `data` DATE NULL,
  `foto` VARCHAR(255) NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  `subtema_id` BIGINT NOT NULL,
  PRIMARY KEY (`id_postagens`, `usuario_id`, `subtema_id`),
  INDEX `fk_tb_postagens_tb_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_tb_postagens_tb_subtemas1_idx` (`subtema_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagens_tb_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_gota_em_gota`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagens_tb_subtemas1`
    FOREIGN KEY (`subtema_id`)
    REFERENCES `db_gota_em_gota`.`tb_subtemas` (`id_temas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
